<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

### Table of Contents

-   [catchAsync][1]

## catchAsync

Returns an async function wrapped in a try catch function. It
will by default log any error thrown in the async function unless
a handleError function is provided. In that case it will instead
call handleError

**Parameters**

-   `asyncFunction` **any** 
-   `options` **[Object][2]?**  (optional, default `{}`)
    -   `options.handleError` **[Function][3]?** if this function is provided
        then catchAsync will call it instead of logging the error
    -   `options.logType`  

Returns **[Function][3]** wrapped async function

[1]: #catchasync

[2]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object

[3]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function
